<h3>Import des différents modules et récupération de la structure</h3>

In [10]:
from numpy import *
from pymatgen.ext.matproj import MPRester
from pymatgen.core import *
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from jupyter_jsmol.pymatgen import quick_view
from ipywidgets import Layout, widgets, interact

with MPRester("VmJsz9RpLnefKgXu") as m: 
    structure = m.get_structure_by_material_id("mp-567636")
    structure.to(filename="VFeSb.cif")


In [23]:
view = quick_view(structure, conventional=True)
display(view)

JsmolView(layout=Layout(align_self='stretch', height='400px'))

<h3>Analyse des symétries du cristal et choix des symétries</h3>

In [44]:
sym = SpacegroupAnalyzer(structure).get_symmetry_operations()

# Symétries choisies pour les atomes
S1 = sym[7]
S2 = sym[10]
S3 = sym[3]

V = array([0.0, 0.0, 0.0])
Fe = array([0.25, 0.25, 0.75])
Sb = array([0, 0, 0.5])

V_sym = S1.operate(V)
Fe_sym = S2.operate(Fe)
Sb_sym = S3.operate(Sb)

<h3>Symmétrie pour le 1er atome</h3>

In [45]:
print("L'atome de départ est le V et a comme coordonnées: {}\n".format(V))
print("On lui applique un plan miroir (z,y,x) : ")
print(S1.rotation_matrix, "*", V, '+', S1.translation_vector)
print("Les coordonnées de l'atome final sont {}\n".format(V_sym))
v1 = jsm.pymatgen.quick_view(structure,conventional=True)
display(v1)
v1.script("draw symop 8 {atomno=1}")

L'atome de départ est le V et a comme coordonnées: [0. 0. 0.]

On lui applique un plan miroir (z,y,x) : 
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]] * [0. 0. 0.] + [0. 0. 0.]
Les coordonnées de l'atome final sont [0. 0. 0.]



JsmolView(layout=Layout(align_self='stretch', height='400px'))

<h3>Symmétrie pour le 2e atome</h3>

In [46]:
print("L'atome de départ est le Fe et a comme coordonnées: {}\n".format(Fe))
print("On lui applique une rotation C3 d'axe [111] (y,z,x) : ")
print(S2.rotation_matrix, "*", Fe, '+', S2.translation_vector)
print("Les coordonnées de l'atome final sont {}\n".format(Fe_sym))
v2 = quick_view(structure,conventional=True)
display(v2)
v2.script("draw symop 11 {atomno=2}")

L'atome de départ est le Fe et a comme coordonnées: [0.25 0.25 0.75]

On lui applique une rotation C3 d'axe [111] (y,z,x) : 
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]] * [0.25 0.25 0.75] + [0. 0. 0.]
Les coordonnées de l'atome final sont [0.25 0.75 0.25]



JsmolView(layout=Layout(align_self='stretch', height='400px'))

<h3>Symmétrie pour le 3e atome</h3>

In [50]:
print("L'atome de départ est le Sb et a comme coordonnées: {}\n".format(Sb))
print("On lui applique une roto-inversion (-x-y-z,x,y) : ")
print(S3.rotation_matrix, "*", Sb, '+', S3.translation_vector)
print("Les coordonnées de l'atome final sont {}\n".format(Sb_sym))
v3 = quick_view(structure,conventional=True)
display(v3)
v3.script("draw SYMOP 4 {atomno=4}")

L'atome de départ est le Sb et a comme coordonnées: [0.  0.  0.5]

On lui applique une roto-inversion (-x-y-z,x,y) : 
[[-1. -1. -1.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]] * [0.  0.  0.5] + [0. 0. 0.]
Les coordonnées de l'atome final sont [-0.5  0.   0. ]



JsmolView(layout=Layout(align_self='stretch', height='400px'))